version: “3.8”

services:

  mysql-db:
    image: mysql:latest
    restart: unless-stopped
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '4000:3306'
    volumes:
      - ./MySql:/var/lib/mysql

  api-gateway:
    build: ./APIGateway
    restart: unless-stopped
    container_name: api-gateway
    ports:
      - '3000:3000'
    volumes:
      - ./APIGateway:/app

  teacherhub-service:
    build: ./TeacherHub
    restart: unless-stopped
    container_name: teacherhub
    ports:
      - '3002:3002'
    volumes:
      - ./TeacherHub:/app
  
  edumanage-service:
    build: ./TeacherHub
    restart: unless-stopped
    container_name: edumanage
    ports:
      - '3001:3001'
    volumes:
      - ./EduManage:/app

volumes:
    - "/etc/timezone:/etc/timezone:ro"
    - "/etc/localtime:/etc/localtime:ro"