version: “3.8”

services:

  mysql-db:
    image: mysql:latest
    restart: unless-stopped
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '4000:3306'
    volumes:
      - ./MySql:/var/lib/mysql

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root     
    ports:
      - '27017:27017'
    volumes:
      - ./MongoDB:/data/db

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    ports:
      - '8081:8081'

  # api-gateway:
  #   build: ./APIGateway
  #   restart: unless-stopped
  #   container_name: api-gateway
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - ./APIGateway:/app

  # user-service:
  #   build: ./User
  #   restart: unless-stopped
  #   container_name: user-service
  #   ports:
  #     - '3001:3001'
  #   volumes:
  #     - ./User:/app
