apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: arete-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: arete-ingress-gateway
      http: 
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: arete-backend-gateway
                port:
                  number: 3000